### ISSUE TITLE
Provide a json-schema definition of etiketo document

### ISSUE THREAD

**Issue by ioggstream** [API-Labels/etiketo#5]
## Idea

Etiketo document can be defined using json-schema instead of ABNF

This would ease phrases like:

```
The value of link labels is either:
- a single URI, which is represented by a single JSON string, 
- or a set of URIs, which is represented by a JSON array of strings.

An array containing a single string is equivalent to that single string without a containing array.
```

**Comment by dret** [comment]
On 2020-01-16 08:07, Roberto Polli wrote:
>     Idea
> Etiketo document can be defined using json-schema instead of ABNF

so far ABNF seems to be the way most IETF specs go. JSON schema is still 
a draft with an unclear future of ever getting finalized as a spec.

**Comment by ioggstream** [comment]
> JSON schema is still a draft with an unclear future
Ok, but I will
